### ISSUE TITLE
Scylla::frame::value::Time doesn’t implement FromCqlVal

### ISSUE THREAD

**Issue by DayOfThePenguin** [scylladb/scylla-rust-driver#421]
I’m trying to create a structure to serialize and deserialize rows of a time series like the example below:

```rust
use chrono::Duration; 
use scylla::frame::value::{MaybeUnset, Time};


#[derive(IntoUserType, FromUserType)]
struct SensorReading {
sensor_id: String,
date: NaiveDate,
time: Time,
other_non_primary_key_field: MaybeUnset<i8>,
}

```

However, it won’t compile with error “the trait bound `scylla::frame::value::Time: FromCqlVal<CqlValue>` is not satisfied.”  I tried changing the type to chrono::Duration (which FromCqlVal is implemented for).  However, because ValueList requires struct member to implement scylla::frame::value::Value, using Duration won’t work because Value is only implemented for Time and not Duration.

I think there are two possibly solutions to this:
1. Implement Value or FromCqlValue for Duration/Time, respectively.
2. Splitting serialization and deserialization structures and having one use Time and the other use Duration to satisfy the trait bounds.  

Which is the intended behavior?

I was also getting similar Value/FromCqlValue trait errors when I tried to implement this as a UDT and use IntoUserType and FromUserType, so I think a similar Duration/Time mismatch might exist there as well.

**Comment by psarna** [comment]
Sounds like we have an extremely similar issue a few days ago (#420) and implementing the missing `FromCqlVal` sounded like the way to go. Specifically, I think here we're missing an implementation for Time, just like we were missing a helper function, `as_time`, similar to [those ones](https://github.com/scylladb/scylla-rust-driver/blob/2cf503bdcdc67a9e7a25fcd2c572737530750628/scylla/src/frame/response/cql_to_rust.rs#L83-L98), which allows deserializing results as `scylla::frame::value::Time`.

**Comment by psarna** [comment]
Oh wait, it looks like I mixed it up. `scylla::frame::value::Time` is an internal representation, so it shouldn't need to implement `FromCqlVal`, as it's not generally expected to be used outside of the crate. I'll investigate some more and come back with a better answer.

**Comment by psarna** [comment]
Alright, I got a little confused at first, but here's my conclusion:

`scylla::frame::value::Time` is an internal type that wasn't supposed to be used directly in structs such as yours, that's why it didn't implement FromCqlValue.

However, `FromCqlValue` is trivially implemented for `scylla::frame::response::result::CqlValue`, so as a trivial workaround you can use that one in your struct, like that:
```rust
#[derive(IntoUserType, FromUserType)]
struct SensorReading {
sensor_id: String,
time: CqlValue,
// and so on
}
```
Then, you can just put `CqlValue::Time` in there when you want to send the request and it will work just fine.
However, we lack a 1:1 mapping from a Rust type to CQL `time` type. That's what our `Value` trait provides, but we can't just implement `impl Value for chrono::Duration` to return time, because Duration can also be used to handle other CQL types, like timestamp, date, and so on. It's only a workaround though, because you lose some type safety here - it's now the programmer's responsibility to always put `CqlValue::Time` in there and nothing else in order for requests to be correct.

So perhaps we need to provide a thin wrapper for time that implements `impl Value for OurWrapperThatSerializesToCQLTime`, which is constructible from chrono::Duration and serializes as `scylla::frame::value::Time`.

@DayOfThePenguin `trait Value` is public, so you can implement such a wrapper yourself, but I suppose we should also provide such mappings for all types. /cc @piodul @havaker

**Comment by psarna** [comment]
Hmm, maybe our internal Time type could already act as such a wrapper... In which case we should just implement FromCqlVal for it and be done with it. It's already a thin wrapper over Duration anyway.

**Comment by psarna** [comment]
Suggested fix: https://github.com/scylladb/scylla-rust-driver/pull/422

**Comment by piodul** [comment]
Implementing `FromCqlVal` for our existing wrapper types (`Time`, `Timestamp`, `Date`) sounds like a good idea.

**Comment by DayOfThePenguin** [comment]
From the reading I did through the codebase, implementing FromCqlValue sounds like a good solution since it preserves the isolation between the CQL Date, Time, and Timestamp types that you've already created

**Comment by piodul** [comment]
@DayOfThePenguin you will encounter a similar problem with `other_non_primary_key_field: MaybeUnset<i8>`, as it only supports serialization. I guess you wanted to be able to represent a value which can optionally be `null` - in such case, you should use `Option<i8>` instead.

MaybeUnset has a different use - it can be used to mark that a particular query binding (the `?` mark) should be ignored. For example, when used in `UPDATE t SET v = ? WHERE pk = 1` it will cause nothing to be written to the column `v`, not even `null`.

**Comment by DayOfThePenguin** [comment]
@piodul yes, my intent with `MaybeUnset` was to be able to optionally mark a column value as null. In the documentation book, it says using `Option` for queries can result in sub-optimal performance because it generates a tombstone and recommends using `MaybeUnset::Unset` instead.

[ref](https://rust-driver.docs.scylladb.com/stable/queries/values.html#unset-values)

**Comment by DayOfThePenguin** [comment]
Although, the issue on the Cassandra Jira that is cited in the [doc-book](https://issues.apache.org/jira/browse/CASSANDRA-7304) as the reason for the use of `Unset` vs `null` (inserts using prepared queries with null fields generating tombstones) seems to have been resolved in Cassandra since 2.2. Is it safe to assume that functionality has made it into Scylla and I can use `Option` without the tombstone issue at high insert rates?

**Comment by psarna** [comment]
Hm, I'd need to check that, but in case of prepared statements in which you don't want to bind to all the values, it's likely we should implement `FromCqlVal` for `MaybeUnset` to allow serializing such a construct.

I never considered it a common case, mainly because you could just prepare another statement with fewer wildcards in case you sometimes want to omit certain fields - but I still agree that we should support binding `Unset` if it's more convenient for some use cases.

**Comment by DayOfThePenguin** [comment]
In my case, I have some sensor readings with 20 fields, up to 15 of which can be nullable for different readings depending on the  type of reading, so the combinatorics of that many unique prepared statements is prohibitive.  I can look at a workaround if it's not a common use case that isn't intended to be supported though.

**Comment by psarna** [comment]
It's fine, even if it's not a common case, it's definitely legal in CQL, so we should allow it in the driver, one way or the other. The simplest step would be to implement FromCqlVal for MaybeUnset. That doesn't solve each case because then you couldn't really express `null` in a struct that uses `MaybeUnset` as one of the attributes, but let's leave more complex cases for later.

**Comment by DayOfThePenguin** [comment]
So I tried implementing this myself, but the problem I'm running into is that since associative type binds aren't supported yet, I can't do it for any generic V that implements Value (i.e. `impl FromCqlVal for crate::frame::value::MaybeUnset<V: Value>`.  The workaround for this seems to be to implement it for `MaybeUnset<CqlValue>` and accept that you have to match for each variant of `CqlValue`. 

```rust
impl FromCqlVal<CqlValue> for crate::frame::value::MaybeUnset<CqlValue> {
    fn from_cql(cql_val: CqlValue) -> Result<Self, FromCqlValError> {
        match cql_val {
            CqlValue::Ascii(_) => todo!(),
            CqlValue::Boolean(_) => todo!(),
            CqlValue::Blob(_) => todo!(),
            CqlValue::Counter(_) => todo!(),
            CqlValue::Decimal(_) => todo!(),
            CqlValue::Date(_) => todo!(),
            CqlValue::Double(_) => todo!(),
            CqlValue::Duration(_) => todo!(),
            CqlValue::Empty => todo!(),
            CqlValue::Float(_) => todo!(),
            CqlValue::Int(_) => todo!(),
            CqlValue::BigInt(_) => todo!(),
            CqlValue::Text(_) => todo!(),
            CqlValue::Timestamp(_) => todo!(),
            CqlValue::Inet(_) => todo!(),
            CqlValue::List(_) => todo!(),
            CqlValue::Map(_) => todo!(),
            CqlValue::Set(_) => todo!(),
            CqlValue::UserDefinedType { keyspace, type_name, fields } => todo!(),
            CqlValue::SmallInt(_) => todo!(),
            CqlValue::TinyInt(_) => todo!(),
            CqlValue::Time(_) => todo!(),
            CqlValue::Timeuuid(_) => todo!(),
            CqlValue::Tuple(_) => todo!(),
            CqlValue::Uuid(_) => todo!(),
            CqlValue::Varint(_) => todo!(),
        }
    }
}
```

This seems to be missing the case for the MaybeUnset::Unset though.  I have a feeling that changes to the generic implementation of `from_cql<Option<CqlValue>>` (lines 61-71 in `cql_to_rust.rs`) might be required too?
